/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSide: typeof import('./src/components/app-side/index.vue')['default']
    ChatContent: typeof import('./src/components/Chat/ChatContent.vue')['default']
    ChatLoading: typeof import('./src/components/Chat/ChatLoading.vue')['default']
    ChatReasoning: typeof import('./src/components/Chat/ChatReasoning.vue')['default']
    DateRange: typeof import('./src/components/DateRange/DateRange.vue')['default']
    EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
    FileCode: typeof import('./src/components/KbIcon/FileCode.vue')['default']
    FileDrauu: typeof import('./src/components/KbIcon/FileDrauu.vue')['default']
    FileEncrypt: typeof import('./src/components/KbIcon/FileEncrypt.vue')['default']
    FileHandsontable: typeof import('./src/components/KbIcon/FileHandsontable.vue')['default']
    FileLct: typeof import('./src/components/KbIcon/FileLct.vue')['default']
    FileMarkdown: typeof import('./src/components/KbIcon/FileMarkdown.vue')['default']
    FileMindMap: typeof import('./src/components/KbIcon/FileMindMap.vue')['default']
    FileRichText: typeof import('./src/components/KbIcon/FileRichText.vue')['default']
    FileSuperNote: typeof import('./src/components/KbIcon/FileSuperNote.vue')['default']
    InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
    Item: typeof import('./src/components/update-check/item.vue')['default']
    KbAlert: typeof import('./src/components/KbAlert/KbAlert.vue')['default']
    LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
    PriorityDropdown: typeof import('./src/components/PriorityDropdown/PriorityDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
    TagGroup: typeof import('./src/components/TagGroup/TagGroup.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    THeader: typeof import('tdesign-vue-next')['Header']
    TImageViewer: typeof import('tdesign-vue-next')['ImageViewer']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TodoDate: typeof import('./src/components/TodoDate/TodoDate.vue')['default']
    TodoItemCheckbox: typeof import('./src/components/TodoItemCheckbox/TodoItemCheckbox.vue')['default']
    UnTopIcon: typeof import('./src/components/KbIcon/UnTopIcon.vue')['default']
    UpdateCheck: typeof import('./src/components/update-check/index.vue')['default']
    UserVipDrawer: typeof import('./src/components/app-side/UserVipDrawer.vue')['default']
    VipIcon: typeof import('./src/components/KbIcon/VipIcon.vue')['default']
  }
}
